### ISSUE TITLE
HA docker container 2024.2.2

### ISSUE THREAD

**Issue by brunopiras** [Kajkac/ZTE-MC-Home-assistant#16]
"Router MC888 Ultra"

Hi, 

try to get any data but there's errors in py scripts:

try in home assistant shell but same result in home assistant logs:
`
apu2:/config# /usr/local/bin/python /config/python_scripts/zte_tool.py 3
Traceback (most recent call last):
  File "/config/python_scripts/zte_tool.py", line 270, in <module>
    result = zteInstance.zteinfo()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/config/python_scripts/zte_tool.py", line 151, in zteinfo
    cookie = self.getCookie(password = self.password, LD = self.get_LD())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/python_scripts/zte_tool.py", line 85, in getCookie
    return "stok=" + r.cookies["stok"].strip('\"')
                     ~~~~~~~~~^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/cookies.py", line 334, in __getitem__
    return self._find_no_duplicates(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/cookies.py", line 413, in _find_no_duplicates
    raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}")
KeyError: "name='stok', domain=None, path=None"
apu2:/config# 
`



HomeAssistant Logs:

`
apu2:/config# cat home-assistant.log | grep zte
2024-02-21 11:09:26.838 ERROR (SyncWorker_38) [homeassistant.components.command_line.utils] Command failed (with return code 1): /usr/local/bin/python /config/python_scripts/zte_tool.py 1
2024-02-21 11:09:27.283 ERROR (SyncWorker_32) [homeassistant.components.command_line.utils] Command failed (with return code 1): /usr/local/bin/python /config/python_scripts/zte_tool.py 1
2024-02-21 11:09:28.080 ERROR (SyncWorker_24) [homeassistant.components.command_line.utils] Command failed (with return code 1): /usr/local/bin/python /config/python_scripts/zte_tool.py 3
2024-02-21 11:09:31.070 ERROR (SyncWorker_58) [homeassistant.components.command_line.utils] Command failed (with return code 1): /usr/local/bin/python /config/python_scripts/zte_tool.py 6
2024-02-21 11:10:19.739 INFO (MainThread) [homeassistant.components.command_line] Running command: /usr/local/bin/python /config/python_scripts/zte_tool.py 2
2024-02-21 11:10:20.026 ERROR (SyncWorker_13) [homeassistant.components.command_line.utils] Command failed (with return code 1): /usr/local/bin/python /config/python_scripts/zte_tool.py 2
2024-02-21 11:10:20.027 ERROR (MainThread) [homeassistant.components.command_line] Command failed: /usr/local/bin/python /config/python_scripts/zte_tool.py 2
2024-02-21 11:10:21.957 INFO (MainThread) [homeassistant.components.command_line] Running command: /usr/local/bin/python /config/python_scripts/zte_tool.py 2
2024-02-21 11:10:22.247 ERROR (SyncWorker_45) [homeassistant.components.command_line.utils] Command failed (with return code 1): /usr/local/bin/python /config/python_scripts/zte_tool.py 2
2024-02-21 11:10:22.247 ERROR (MainThread) [homeassistant.components.command_line] Command failed: /usr/local/bin/python /config/python_scripts/zte_tool.py 2
2024-02-21 11:10:29.388 INFO (MainThread) [homeassistant.components.command_line] Running command: /usr/local/bin/python /config/python_scripts/zte_tool.py 1
2024-02-21 11:10:31.684 ERROR (SyncWorker_50) [homeassistant.components.command_line.utils] Command failed (with return code 1): /usr/local/bin/python /config/python_scripts/zte_tool.py 1
2024-02-21 11:10:31.685 ERROR (MainThread) [homeassistant.components.command_line] Command failed: /usr/local/bin/python /config/python_scripts/zte_tool.py 1
2024-02-21 11:14:36.350 ERROR (SyncWorker_10) [homeassistant.components.command_line.utils] Command failed (with return code 1): /usr/local/bin/python /config/python_scripts/zte_tool.py 3
2024-02-21 11:19:41.390 ERROR (SyncWorker_49) [homeassistant.components.command_line.utils] Command failed (with return code 1): /usr/local/bin/python /config/python_scripts/zte_tool.py 3
2024-02-21 11:22:57.372 ERROR (SyncWorker_30) [homeassistant.components.command_line.utils] Command failed (with return code 1): /usr/local/bin/python /config/python_scripts/zte_tool.py 6
2024-02-21 11:24:29.153 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): /usr/local/bin/python /config/python_scripts/zte_tool.py 1
2024-02-21 11:24:46.570 ERROR (SyncWorker_13) [homeassistant.components.command_line.utils] Command failed (with return code 1): /usr/local/bin/python /config/python_scripts/zte_tool.py 3
2024-02-21 11:29:51.378 ERROR (SyncWorker_3) [homeassistant.components.command_line.utils] Command failed (with return code 1): /usr/local/bin/python /config/python_scripts/zte_tool.py 3
2024-02-21 11:34:56.381 ERROR (SyncWorker_26) [homeassistant.components.command_line.utils] Command failed (with return code 1): /usr/local/bin/python /config/python_scripts/zte_tool.py 3
2024-02-21 11:36:17.356 ERROR (SyncWorker_63) [homeassistant.components.command_line.utils] Command failed (with return code 1): /usr/local/bin/python /config/python_scripts/zte_tool.py 6
`

**Comment by brunopiras** [comment]
Hello there,

I think the problem is about user and password, because my router to web login ask me both, user and password, Username can't be changed is "User", the password can be changed by web ui.

**Comment by Kajkac** [comment]
Did u use in configuration username and password? Default now is admin admin but it should be configurable.

**Comment by brunopiras** [comment]
> Did u use in configuration username and password? Default now is admin admin but it should be configurable.

I did,

changed ip, username and password but this is the output:

`apu2:/config# python python_scripts/zte_tool.py 3
Traceback (most recent call last):
  File "/config/python_scripts/zte_tool.py", line 317, in <module>
    result = zteInstance.zteinfo()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/config/python_scripts/zte_tool.py", line 162, in zteinfo
    cookie = self.getCookie(username=self.username, password=self.password, LD=self.get_LD())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/python_scripts/zte_tool.py", line 96, in getCookie
    return "stok=" + r.cookies["stok"].strip('\"')
                     ~~~~~~~~~^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/cookies.py", line 334, in __getitem__
    return self._find_no_duplicates(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/cookies.py", line 413, in _find_no_duplicates
    raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}")
KeyError: "name='stok', domain=None, path=None"`

Any help?

Thanks

**Comment by brunopiras** [comment]
I solved myself, sell the MC888 Ultra and bought MC888.
